#!/usr/bin/env node

import chalk from "../source/index.js";
import fs from "fs";
import path from "path";

const htmlChalk = new chalk.constructor({ formatter: "html" });

// Sample content to demonstrate different styles
const samples = [
	{ text: "Error Message", style: htmlChalk.red.bold },
	{ text: "Warning Message", style: htmlChalk.yellow.bold },
	{ text: "Success Message", style: htmlChalk.green.bold },
	{ text: "Info Message", style: htmlChalk.blue.bold },
	{ text: "Code Example", style: htmlChalk.cyan.italic },
	{ text: "Important Note", style: htmlChalk.magenta.underline },
	{ text: "Background Highlight", style: htmlChalk.bgBlue.white.bold },
	{
		text: "Multiple Styles",
		style: htmlChalk.red.bgYellow.bold.italic.underline,
	},
];

// Generate HTML content
const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Chalk HTML Preview</title>
	<style>
		body {
			font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
			background-color: #1e1e1e;
			color: #ffffff;
			padding: 2rem;
			line-height: 1.6;
		}
		.container {
			max-width: 800px;
			margin: 0 auto;
		}
		h1 {
			color: #61afef;
			border-bottom: 2px solid #61afef;
			padding-bottom: 0.5rem;
		}
		.sample {
			margin: 1rem 0;
			padding: 1rem;
			background-color: #2d2d2d;
			border-radius: 4px;
		}
		.label {
			font-size: 0.9rem;
			color: #888;
			margin-bottom: 0.5rem;
		}
		.output {
			font-size: 1.1rem;
		}
		.code {
			background-color: #3c3c3c;
			padding: 1rem;
			border-radius: 4px;
			margin: 1rem 0;
			overflow-x: auto;
		}
		.footer {
			margin-top: 2rem;
			padding-top: 1rem;
			border-top: 1px solid #444;
			color: #888;
			font-size: 0.9rem;
		}
	</style>
</head>
<body>
	<div class="container">
		<h1>🎨 Chalk HTML Formatter Preview</h1>
		
		<p>This page demonstrates the HTML output generated by Chalk's HTML formatter. Each sample shows how different chalk styles are converted to HTML with inline CSS.</p>
		
		<div class="code">
			<strong>Usage Example:</strong><br>
			<code>const htmlChalk = new chalk.constructor({ formatter: 'html' });<br>
			console.log(htmlChalk.red.bold('Hello World'));</code>
		</div>
		
		<h2>Style Samples:</h2>
		
		${samples
			.map(
				(sample, index) => `
			<div class="sample">
				<div class="label">Sample ${index + 1}: ${sample.text}</div>
				<div class="output">${sample.style(sample.text)}</div>
			</div>
		`
			)
			.join("")}
		
		<h2>Advanced Examples:</h2>
		
		<div class="sample">
			<div class="label">Nested Styles:</div>
			<div class="output">
				${htmlChalk.green(
					"Green text with " + htmlChalk.red.bold("bold red") + " nested inside"
				)}
			</div>
		</div>
		
		<div class="sample">
			<div class="label">RGB Colors:</div>
			<div class="output">
				${htmlChalk.rgb(255, 100, 150).bold("Custom RGB color")}
			</div>
		</div>
		
		<div class="sample">
			<div class="label">Hex Colors:</div>
			<div class="output">
				${htmlChalk.hex("#FF6B6B").italic("Custom hex color")}
			</div>
		</div>
		
		<div class="footer">
			<p>Generated by Chalk with Pluggable Formatters</p>
			<p>Available formatters: ${chalk.listFormatters().join(", ")}</p>
		</div>
	</div>
</body>
</html>
`;

// Write HTML file
const outputPath = path.join(process.cwd(), "chalk-preview.html");
fs.writeFileSync(outputPath, htmlContent);

console.log("🎨 HTML preview generated!");
console.log(`📁 File saved to: ${outputPath}`);
console.log("🌐 Open the file in your browser to see the preview");
console.log("\n💡 You can also run:");
console.log(`   open ${outputPath}  # macOS`);
console.log(`   xdg-open ${outputPath}  # Linux`);
console.log(`   start ${outputPath}  # Windows`);

// Also show some console output
console.log("\n📋 Console Preview:");
samples.forEach((sample, index) => {
	console.log(`Sample ${index + 1}: ${sample.style(sample.text)}`);
});
